### ISSUE TITLE
Missing cfg folder

### ISSUE THREAD

**Issue by masonr** [marcoboogers/soccermod#1]
Would it be possible to add the config files to the project?
-  gamemode_casual_server.cfg
- gamemode_competitive_server.cfg
- gamemode_custom_server.cfg

**Comment by marcoboogers** [comment]
It would be possible, but I don't think they should be added. I don't want to overwrite any existing files on the server.

PS: sorry for the late reply. I didn't notice that you had posted something here :)

**Comment by masonr** [comment]
@marcoboogers - No worries :)

That makes sense and is fine. I'd suggest at least adding a Wiki page with a sample config because it took me quite some time to figure out the right settings for the player and ball models. And I'm sure I've misconfigured something.

**Comment by marcoboogers** [comment]
I was planning on adding a readme, but I have a guide on Steam: http://steamcommunity.com/sharedfiles/filedetails/?id=267151106

Feel free to add me on Steam if you have a question.

**Comment by masonr** [comment]
Awesome, will do. Thanks!
